### ISSUE TITLE
balloon_min fehlt im Adapter

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.proxmox#101]
Hallo,
Da ich im Proxmox den minimalen Speicher mit angegeben habe, meckert IoBroker, dass der Wert nicht als Onbjekt da sei. 
Habe ihn erstmal "zu Fuß" angelegt, wäre schön, wenn er im Adapter fest installiert wäre.
Danke!

**Comment by foxriver76** [comment]
Wie hast du diesen mit angegeben? Damit man das reproduzieren und einbauen kann? ;-)

**Comment by guergen1** [comment]
So (Sorry für das delay, hatte die Reaktion auf meinen Issue nicht gesehen):
`{
  "from": "system.adapter.proxmox.0",
  "user": "system.user.admin",
  "ts": 1580636353341,
  "common": {
    "name": "balloon_min",
    "role": "value",
    "type": "number",
    "write": false,
    "read": true,
    "unit": "MiB"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "proxmox.0.qemu_deconz.balloon_min",
  "type": "state"
}`

**Comment by klein0r** [comment]
Sollte eigentlich mittlerweile erstellt werden

https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/a7c203ad9ac155c6dbba9dd7d630b5a3d243853a/main.js#L747
