### ISSUE TITLE
which role is necessary for vm status?

### ISSUE THREAD

**Issue by tis-cs** [iobroker-community-adapters/ioBroker.proxmox#109]
I created an new status user in my pve and connected it successfully but I won't get new objects and can't control the pve via iobroker.

Which minimum role is necessary? I won't connect with my root ;)

Thanks in advance!

**Comment by arteck** [comment]
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/1c7477b1-81e5-4680-a005-337565815d7f)
