### ISSUE TITLE
[Feature Request] Backup states

### ISSUE THREAD

**Issue by Mic-M** [iobroker-community-adapters/ioBroker.proxmox#11]
Hi,
Many thanks for the adapter, great for visualization and re-acting through JavaScript in case of issues.
As an enhancement request:
It would be great to have states available for backup, specifically scheduled backups which are set up under “Datacenter > Backup”, including states which indicate that the backup was performed and/or successful.
Thanks.

**Comment by Leviathan09** [comment]
Maybe also trigger Backups would be nice if this is possible

**Comment by huperis** [comment]
I would also like the feature very well. Is there any feedback on whether this will be implemented?

**Comment by Amokd0c** [comment]
That would be really really great! I've been looking for a way to display the backup status in my visualization for ages! I would donate something too! :)

**Comment by arteck** [comment]
this request is a performace killer

![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/9e3dfb82-3b9c-490e-ad17-4f60e8a57e97)

maybe for small architecture.. i have on my storage 1000 backups ...

**Comment by arteck** [comment]
check GIT version.. 
and select 
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/9230492b-bee5-484a-baff-70fc357e383f)

you have a new object
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/060b7640-0649-4ed5-8f06-2c97916e5489)

with JSON 

![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/bf4860c4-9263-4981-842a-3bce0c9ead35)
