### ISSUE TITLE
in new Admin 5 : state value is wrong

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.proxmox#110]
![grafik](https://user-images.githubusercontent.com/6681528/115967279-0f629980-a532-11eb-9db9-854396c65378.png)

**Comment by kueppert** [comment]
anbei auch einige Meldungen von mir (JS-COntroller 3.3) in Textform:
proxmox.0 | 2021-04-30 10:14:19.193 | warn | (12601) State value to set for "proxmox.0.qemu_MySQL.pid" has wrong type "string" but has to be "number"
proxmox.0 | 2021-04-30 10:14:19.125 | warn | (12601) State value to set for "proxmox.0.qemu_ioBroker.pid" has wrong type "string" but has to be "number"
proxmox.0 | 2021-04-30 10:14:18.932 | warn | (12601) State value to set for "proxmox.0.qemu_Unifi.pid" has wrong type "string" but has to be "number"
proxmox.0 | 2021-04-30 10:14:18.829 | warn | (12601) State value to set for "proxmox.0.qemu_piHole.pid" has wrong type "string" but has to be "number"
proxmox.0 | 2021-04-30 10:14:18.778 | warn | (12601) State value to set for "proxmox.0.qemu_TasmoAdmin.pid" has wrong type "string" but has to be "number"
proxmox.0 | 2021-04-30 10:14:18.621 | warn | (12601) State value to set for "proxmox.0.node_proxmox.status" has wrong type "string" but has to be "boolean"
proxmox.0 | 2021-04-30 10:13:19.116 | warn | (12601) State value to set for "proxmox.0.qemu_ioBroker.pid" has wrong type "string" but has to be "number"

**Comment by foxriver76** [comment]
Should be fixed with latest version
