### ISSUE TITLE
State "proxmox.0.lxc_pihole.pid" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.proxmox#139]
obiger Fehler tritt bei dieser 1 LXC auf (heute erstellt).
bei älteren LXC kommt der Fehler nicht.

Systemkonfig:
JS-Controller: 3.3.14
NODE.JS: V14.17.1
NPM: 6.14.13
Admin: 5.1.15
Proxmoxadapter: 1.3.4

**Comment by thost96** [comment]
Duplicate of #133 as these warnings are added with js-controller 3.3
