### ISSUE TITLE
Unable to login to proxmox with pam user

### ISSUE THREAD

**Issue by weidlix** [iobroker-community-adapters/ioBroker.proxmox#143]
proxmox.0 | 2021-08-30 15:59:02.363 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
proxmox.0 | 2021-08-30 15:59:02.361 | error | Unable to authenticate with Proxmox host. Please check your credentials
proxmox.0 | 2021-08-30 15:59:02.358 | error | 404: Error: connect EHOSTUNREACH 192.168.178.188:8006

IP and password are correct. I can login via Proxmox UI. It does nor work since months but worked when I installad the adapter last year

**Comment by thost96** [comment]
Noticed something similar. Have you tried to reenter all settings into the instance configuration and select pam again? 
For me, it works to select pam and reenter the password every time you change something on the instance settings.

**Comment by Suschibomber** [comment]
Same for me. After stopping the Adapter and reenter the User and PW and choose pam the adapter did not connect to the proxmox anymore :(

**Comment by klein0r** [comment]
Please test with 2.0.0
