### ISSUE TITLE
Datapoint "status" of VM unstable

### ISSUE THREAD

**Issue by maddogsg** [iobroker-community-adapters/ioBroker.proxmox#158]
Dear all, I am using iobroker and this proxmox adapter several times now and the datapoint "state" always detects the state of the VM machine as "running and stopped" in unperiodic change while the machine is running permanently. Any suggestions / fixes to fix this?

admin: 5.1.25
js: 5.2.13
npm: 8.1.0
node: 16.12.0
proxmox adapter: 1.3.4

**Comment by arteck** [comment]
check my GIT version https://github.com/arteck/ioBroker.proxmox
