### ISSUE TITLE
SInce adding Proxmox Backup Serve (PBS) warnings in log window

### ISSUE THREAD

**Issue by simpixo** [iobroker-community-adapters/ioBroker.proxmox#161]
Since i add the Proxmox Backup Server to my proxmox environment i get many warning messages in log window. how can i stop this? The IP showing in the states is my PBS. the messages appears periodically

example of warnings

proxmox.0 | 2021-10-26 21:29:00.965 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
proxmox.0 | 2021-10-26 21:29:00.965 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used_lev" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.avail" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.total" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.active" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.enabled" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.shared" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.content" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.type" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used_lev" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.avail" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.964 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.total" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.963 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.active" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.963 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.enabled" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.963 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.shared" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.963 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.content" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:29:00.963 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.type" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.934 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.active" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.933 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.933 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.used_lev" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.933 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.avail" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.933 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.total" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.932 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.type" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.932 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.content" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.932 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.enabled" has no existing object, this might lead to an error in future versions
proxmox.0 | 2021-10-26 21:28:30.932 | warn | (8236) State "proxmox.0.storage_PBS_192.168.160.127.shared" has no existing object, this might lead to an error in future versions

**Comment by Negalein** [comment]
selbes Problem seit  den Backups

`has no existing object, this might lead to an error in future versions`

**Comment by klein0r** [comment]
Please test with 2.0.2
