### ISSUE TITLE
State "proxmox.0.qemu_xyz.pid" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by passuff** [iobroker-community-adapters/ioBroker.proxmox#177]
Diese Fehlermeldung erhält man, wenn man in Proxmox einen qmu/lxc hinzufügt ohne den proxmox Adapter in iobroker neuzustarten.
Wie es scheint, legt er die Objekte nur bei einem neustart an.

**Comment by Diginix** [comment]
Generell gibt es Fehler im Log wenn man in Proxmox etwas anpasst/hinzufügt und der state vom Adapter geschrieben werden will ohne das der Adapter zuvor das Objekt initial erstellt hat.
`proxmox.0 2022-02-11 13:18:15.239	warn	State "proxmox.0.qemu_iobroker.balloon_min" has no existing object, this might lead to an error in future versions`

Es sollte also vor dem Schreiben jedes Wertes geprüft werden ob das Objekt dazu existiert. Falls nicht, muss es erstellt werden.
