### ISSUE TITLE
Feature request: Add instance

### ISSUE THREAD

**Issue by Bark33p3r** [iobroker-community-adapters/ioBroker.proxmox#185]
Hello there,

may it's possible to add an instances link on the instances list, like in node red e.g.

![image](https://user-images.githubusercontent.com/65457605/152828588-d660cc41-1b33-4f05-a346-992bf31268d4.png)

Thanks

**Comment by thost96** [comment]
Hi @Bark33p3r,

thanks for that request. I added a PR to add this functionality to the proxmox adapter. If you like to test you can use the URL https://github.com/thost96/ioBroker.proxmox/tree/instance-link on the Adapters Tab using the GitHub install as an expert, or you wait until this is merged.

**Comment by Bark33p3r** [comment]
Great, that is awesome and quick.
Seems that it works without any trouble. If you want to you can push it to the master.

Thanks a lot!

**Comment by thost96** [comment]
I would like to get it into a new release, but i don't have permissions for that :-D
