### ISSUE TITLE
status field is not updated (remains null)

### ISSUE THREAD

**Issue by IoTAntimon** [iobroker-community-adapters/ioBroker.proxmox#193]
The state "status" for of qemu_*, node_* and lxc_* is null, although a connection to the proxmox host is active.
In the log, the current status is displayed, but the state is not updated.

Example log: 
> found  states:_[["proxmox.0.qemu_VM  204","status","status","stopped"],["proxmox.0.qemu_VM  204","uptime","time",0],["proxmox.0.qemu_VM  204","diskwrite","size",0],["proxmox.0.qemu_VM  204","netin","sizeb",0],["proxmox.0.qemu_VM  204","cpu","level",0],["proxmox.0.qemu_VM  204","cpus","default_num",1],["proxmox.0.qemu_VM  204","disk_lev","level",null],["proxmox.0.qemu_VM  204","disk","size",0],["proxmox.0.qemu_VM  204","netout","sizeb",0],["proxmox.0.qemu_VM  204","maxdisk","size",0],["proxmox.0.qemu_VM  204","maxmem","size",128],["proxmox.0.qemu_VM  204","mem_lev","level",0],["proxmox.0.qemu_VM 204","mem","size",0]]

Adapter version: 1.3.4
Node.js: v14.18.2
NPM: 6.14.15

**Comment by klein0r** [comment]
Fixed in 2.0.0
