### ISSUE TITLE
proxmox.0.lxc_MotionEye-Backup.pid has no existing object

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.proxmox#195]
Ich denke die Fehlerbeschreibung steht für sich selbst.

Proxmox Adapter 1.3.4

PlatformBetriebssystem:win32
Architektur:x64
CPUs:4
Geschwindigkeit:1995 MHz
Modell:Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM:7.9 GB
Node.js:v14.16.0
timeOffset:-60
NPM:6.14.11

<html>
<body>

proxmox.0 | 6700 | 2022-03-02 19:37:28.814 | warn | State "proxmox.0.lxc_MotionEye-Backup.pid" has no existing object, this might lead to an error in future versions
-- | -- | -- | -- | --
proxmox.0 | 6700 | 2022-03-02 19:36:58.795 | warn | State "proxmox.0.lxc_MotionEye-Backup.pid" has no existing object, this might lead to an error in future versions
proxmox.0 | 6700 | 2022-03-02 19:36:28.811 | warn | State "proxmox.0.lxc_MotionEye-Backup.pid" has no existing object, this might lead to an error in future versions

</body>
</html>

**Comment by arteck** [comment]
starte den adapter neu dann ist es da

**Comment by klein0r** [comment]
Das sollte mit den aktuellen Adapter-Versionen nicht mehr auftreten. Ansonsten bitte einen neuen Issue aufmachen
