### ISSUE TITLE
Since JS Controller 4.0.21 has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by gelberlemmy** [iobroker-community-adapters/ioBroker.proxmox#204]
**Sinvce the new Version of JS Controller is have many "has no existing object, this might lead to an error in future versions"
in my LOG. 
Can you please fix it ?

André**

`proxmox.0 | 2022-03-17 08:06:14.754 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.active" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
proxmox.0 | 2022-03-17 08:06:14.754 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.used" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.754 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.used_lev" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.753 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.total" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.753 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.content" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.753 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.shared" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.753 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.type" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.752 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.enabled" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:06:14.751 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.avail" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.192 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.type" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.192 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.enabled" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.191 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.avail" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.191 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.content" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.189 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.total" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.181 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.shared" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.181 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.used" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.180 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.used_lev" has no existing object, this might lead to an error in future versions
proxmox.0 | 2022-03-17 08:05:48.180 | warn | (3942) State "proxmox.0.storage_Backup-Proxmox.active" has no existing object, this might lead to an error in future versions`

**Comment by klein0r** [comment]
Please test with 2.0.0
