### ISSUE TITLE
Error: "Cannot read property 'then' of undefined"

### ISSUE THREAD

**Issue by Trrw** [iobroker-community-adapters/ioBroker.proxmox#206]
Hello,

I got this "then" Error:
<img width="1636" alt="Bildschirmfoto 2022-04-01 um 08 40 27" src="https://user-images.githubusercontent.com/24519230/161209532-8979aeb6-456c-4b1a-a872-da47644e0f0d.png">

Thank you :)

**Comment by klein0r** [comment]
Please test with 2.0.0
