### ISSUE TITLE
adapter failed after restart if one cluster node is powered down

### ISSUE THREAD

**Issue by MarkSau** [iobroker-community-adapters/ioBroker.proxmox#22]
Hi..
Folgende Situation bei meinem jetzigen 3 Node Cluster:
- Alle Cluster Nodes sind oben, Der Proxmox Adapter läuft.
- Ein Node wird runtergefahren. Proxmox Adapter läuft immer noch.
- Die Node ist weiterhin unten, aber ich restarte den Adapter. Nun bekomme ich jede Menge Fehler

[proxmox_debug.txt](https://github.com/iobroker-community-adapters/ioBroker.proxmox/files/3042334/proxmox_debug.txt)

**Comment by MeisterTR** [comment]
fixed
