### ISSUE TITLE
Get Temperature Data from proxmox

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.proxmox#222]
on pve there is the tool ```apt-get install lm-sensors``` installed 
and the ```sensors-detect``` was running for activate in ```/etc/modules```.
`/etc/init.d/kmod start` is initialized.
So is it possible to get the data as ioBroker-objects?

**Comment by bambi-arch** [comment]
Temperatur der CPU wäre spitze als neuer DP!

**Comment by klein0r** [comment]
Es wird die Standard Proxmox-API genutzt. Wenn diese die Temperatur-Werte nicht bereitstellt, wird es sehr umständlich diese zu holen. Da kommt man mit dem Linux-Adapter sicher weiter als hier.

Siehe auch https://forum.proxmox.com/threads/temperature.67755/page-3

**Comment by arteck** [comment]
this is a proxmox adapter ..and proxmox has not this value..
