### ISSUE TITLE
Start/Stop/Reboot VMs and Reboot/Shutdown Nodes?

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.proxmox#25]
It would be great to also be able to start/stop/reboot VMs and to Reboot/Shutdown ProxMox nodes ...

**Comment by liv-in-sky** [comment]
I agree absolutly - would be a big benefit

**Comment by MeisterTR** [comment]
in progress...

**Comment by MeisterTR** [comment]
done

**Comment by Apollon77** [comment]
Coooool. Need to test soon
