### ISSUE TITLE
Akkustatus Laptop auslesen

### ISSUE THREAD

**Issue by biker1602** [iobroker-community-adapters/ioBroker.proxmox#259]
Hallo
Ich nutze Proxmox auf einem Laptop dazu den iobroker. Gibt es die Möglichkeit etwas mit einzubauen, das den Akkustatus in % mit ausliest.
Ich erhalte unter Proxmox in der Konsole vom ioBroker mit dem Befehl  "acpi --ac-adapter --battery" die aktuelle Prozentzahl des Akkus und ob er am Strom angeschlossen ist oder nicht.
root@iobroker:~# acpi --ac-adapter --battery
Battery 0: Discharging, 86%, 04:12:11 remaining
Adapter 0: off-line

Ich würde das gerne durch eine schaltbare Steckdose mit einem Blockly automatisch ein bzw. ausschalten lassen. Dazu bräuchte ich den % Datenpunkt im iobroker unter Proxmox.
Es wäre sehr schön, wenn man das realisieren könnte.
Danke

**Comment by klein0r** [comment]
> Gibt es die Möglichkeit etwas mit einzubauen, das den Akkustatus in % mit ausliest.

Der Adapter nutzt die Proxmox-API. Also alles, was Du auf der Weboberfläche von Proxmox siehst, kann man auch über die API abfragen. Siehe https://pve.proxmox.com/pve-docs/api-viewer/

Falls da der Akkustand nicht bei ist, dann geht es nicht.

**Comment by arteck** [comment]
Das wird auch nicht sein.. genauso wie die Temperaturen der CPU ect..
Proxmox ist dafür nicht geignet..

**Comment by Ilovegym66** [comment]
Den Befehl kannst du mit dem linux-Control Adapter laufen lassen..
