### ISSUE TITLE
Read and Show HA/Cluster status

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.proxmox#26]
it would be great to also see the HA/Cluster Status

**Comment by MeisterTR** [comment]
i only have one server with one node so i cant test an implement it

**Comment by Apollon77** [comment]
If you need example output for calls simply tell :-)

**Comment by MeisterTR** [comment]
das wäre super

**Comment by Apollon77** [comment]
Dann sag welche States relevant wären

**Comment by Ilovegym66** [comment]
I can support you with tests... 
![grafik](https://user-images.githubusercontent.com/36229898/89264252-e6f8df00-d632-11ea-8274-026855444169.png)

**Comment by Apollon77** [comment]
:_) The question is more which "HA/Cluster features would be relevant to see/control via the adapter.

**Comment by Ilovegym66** [comment]
to see:  Quorate, Nodes on/offline, summary of CPU, Memory, Storage, status of Replication, HA, Ceph.
to control: Backup, Replication, HA, and if possible to migrate a VM/CT. 

And I would like a nice feature to start a snapshot/backup of any VM/CT ( useful with iobroker updates :-)) automatically...

**Comment by arteck** [comment]
done
