### ISSUE TITLE
feature request: SMART Werte und wearout als Datenpunkt

### ISSUE THREAD

**Issue by nicomania** [iobroker-community-adapters/ioBroker.proxmox#273]
Hallo,
ist es möglich die wichtigsten Daten der Festplatte (SMART und Wearout) als Datenpunkt bereit zu stellen? Dann könnte man die Gesundheit der Platte im Auge behalten und auch Alarme einrichten. Das wäre klasse. 
Besten Dank!

![image](https://user-images.githubusercontent.com/35151132/230068078-e8c9735a-58cb-4ff6-bd3c-b8ffe8fa8637.png)

![image](https://user-images.githubusercontent.com/35151132/230072548-bd585f84-ef66-413d-af72-f4ce80ee8f88.png)

**Comment by Muegic** [comment]
Wenn möglich bitte auch gleich die Temperatur mit reinnehmen. (In meinem passiv gekühlten Gehäuse wird es zu muckelig :)

**Comment by nicomania** [comment]
Vielen Dank, funktioniert prima!
