### ISSUE TITLE
wearout wrong type

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.proxmox#296]
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/85553061-9935-4e15-9684-97bb3f1cda84)

![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/7a7d8bf8-b0b8-45e0-ac82-6e975972102b)

**Comment by klein0r** [comment]
Please share the debug log / response of the api

**Comment by klein0r** [comment]
Please test with 2.0.2

**Comment by arteck** [comment]
jetzt ist es garnicht da
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/b06bccc4-4079-4b03-ae3b-f221ddf3c955)

**Comment by klein0r** [comment]
Ja, der liefert bei Dir ja auch keine gültigen Daten. Wird also nicht angelegt.
Das habe ich so übernommen wie der Proxmox-Adapter das auch mit allen anderen States macht.

**Comment by arteck** [comment]
somit liefern alle 5 nodes keine Daten ??

**Comment by klein0r** [comment]
Schau in den HTTP Response

**Comment by arteck** [comment]
ich schau mir das ganze heute abend mal an.. bei  mir wird in der neuen Version nichts mehr aktualisiert.. wenn 1 oder mehr nodes m cluster offline sind... 
der adapter funktioneirt zur Zeit nur mit 1 Node ..
