### ISSUE TITLE
V2.0.x No update of the data points swap

### ISSUE THREAD

**Issue by MK-66** [iobroker-community-adapters/ioBroker.proxmox#298]
With version 2.0.x the data points under swap do not update anymore.

With version 1.3.5 they are still updated normally.

**Comment by klein0r** [comment]
Please share a log in debug mode

**Comment by MK-66** [comment]
Please find attached as a txt file my Proxmox debug log from today.
Below you can also see a screenshot, that the datapoints under swap (node_pve) are not updated in contrast to the CPU datapoint.

![Proxmox Screenshot Swap Datapoints](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/56516310/357fe6e4-9e99-4dbd-96dc-bab5643f0661)

[Proxmox Debug Log.txt](https://github.com/iobroker-community-adapters/ioBroker.proxmox/files/12599209/Proxmox.Debug.Log.txt)

**Comment by klein0r** [comment]
Looks the swap is not used on your system - so the value never changes. State is just updated if the value has changed:

```json
        "swap": {
            "used": 0,
            "total": 7516188672,
            "free": 7516188672
        },
```

**Comment by MK-66** [comment]
That is correct that my swap does not change or is not used, but in V1.3.5 the timestamps of the swap data points were still updated every 30s like all the others.
Then just a quick question to understand: Has this way of updating been changed with V2.0.x so that the timestamp only updates when the values change?

**Comment by klein0r** [comment]
> Then just a quick question to understand: Has this way of updating been changed with V2.0.x so that the timestamp only updates when the values change?

Yes

**Comment by MK-66** [comment]
Ok, thanks a lot and sorry for opening the issue
