### ISSUE TITLE
if node is not available adapter crashed in version 2.0.2

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.proxmox#299]
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/1e1bd01f-82ad-4d51-a1b0-15cc9cc7f61d)

adapterversion : 2.0.2
admin: 6.10.1
js-controller : 5.0.12
node 18

**Comment by mcm1957** [comment]
Please add all version numbers

adapter
admin
js-controller
node

**Comment by arteck** [comment]
plz recheck this branch

https://github.com/iobroker-community-adapters/ioBroker.proxmox/tarball/node_offline

**Comment by klein0r** [comment]
Strange commit messages and a lot of reverted changes?!

https://github.com/iobroker-community-adapters/ioBroker.proxmox/compare/master...node_offline

**Comment by arteck** [comment]
sry ?? 
you can check this with 3 nodes.. when 1 node is offline the adapter crashed 
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/cdb3fa36-6b56-41b3-b088-5c95a1acfea4)

**Comment by arteck** [comment]
i found a simpler method without crash is here...

https://github.com/arteck/ioBroker.proxmox/blob/49a7f48529c4b0f42409ce080da7d6084695d22e/lib/proxmox.js#L265

if the response is undefined then is the node offline

![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/62a03b1d-e1e7-4ceb-a960-f398bf96b946)

**Comment by arteck** [comment]
i have no actual status, no  all the node infos are old... i close here.. and check the adapter later..
