### ISSUE TITLE
adapter crash during set object (button)

### ISSUE THREAD

**Issue by darkman242** [iobroker-community-adapters/ioBroker.proxmox#302]
### The problem

if an LXC is to be started or stopped via an object and Button object time-delayed is set to False(Object tree or Blockly script) the adapter crashes. it worked like this with adapter version 1.3.5

![image](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/46793576/0b640451-d3ef-4bed-931f-c96503a8cd7b)

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

2.0.2

### Version of Proxmox

8

### Operating system running ioBroker

Debain 12

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

`<html>
<body>

host.iobroker | 2023-09-18 10:35:25.203 | error | instance system.adapter.proxmox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
proxmox.0 | 2023-09-18 10:35:25.114 | error | undefined
proxmox.0 | 2023-09-18 10:35:25.114 | error | unhandled promise rejection: undefined
proxmox.0 | 2023-09-18 10:35:25.114 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
proxmox.0 | 2023-09-18 10:35:25.112 | error | received 500 response from /nodes/pve-01/lxc/1500/status/start with content: {"data":null}
proxmox.0 | 2023-09-18 10:35:25.101 | error | undefined
proxmox.0 | 2023-09-18 10:35:25.101 | error | unhandled promise rejection: undefined
proxmox.0 | 2023-09-18 10:35:25.101 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
proxmox.0 | 2023-09-18 10:35:25.098 | error | received 500 response from /nodes/pve-01/lxc/1500/status/start with content: {"data":null}
proxmox.0 | 2023-09-18 10:35:25.087 | error | undefined

</body>
</html>`

**Comment by arteck** [comment]
check GIT version
