### ISSUE TITLE
[JsonConfig] Cannot parse json5 config!

### ISSUE THREAD

**Issue by Bulls91** [iobroker-community-adapters/ioBroker.proxmox#304]
### The problem

Hallo zusammen,
wenn ich den Adapter installiere und die Instanz starten möchte bekomme ich folgende Fehlermeldung:

**[JsonConfig] Cannot parse json5 config!**

Ich kann die Instanz nicht starten und keine Einstellungen vornehmen. Kann mir jemand weiterhelfen?

Vielen Dank im voraus!

### Version of nodejs

v18.18.0

### Version of ioBroker js-controller

 5.0.12

### Version of Adapter

2.0.2

### Version of Proxmox

8.0

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by mcm1957** [comment]
This as / was an admin 6.10.3 problem which is fixed with 6.10.4
