### ISSUE TITLE
proxmox.*.vmid has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.proxmox#305]
### The problem

> 2023-09-26 07:49:57.436	info	State value to set for "proxmox.0.qemu_iobroker.vmid" has to be type "string" but received type "number"
> 2023-09-26 07:49:57.968	info	State value to set for "proxmox.0.qemu_OpenMediaVault.vmid" has to be type "string" but received type "number"
> 2023-09-26 07:49:58.158	info	State value to set for "proxmox.0.lxc_influxdb.vmid" has to be type "string" but received type "number"

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

2.1.0

### Version of Proxmox

7.4-16

### Operating system running ioBroker

Ubuntu LTS

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by arteck** [comment]
check GIT version

**Comment by arteck** [comment]
check adapter settings

**Comment by arteck** [comment]
corr
