### ISSUE TITLE
Update von 2.0.2 auf 2.1.0 löscht den Datenbaum

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.proxmox#306]
### The problem

Beim Update von 2.0.2 auf 2.1.0 wurde fast der komplette Datenpunkte-Baum vom Proxmox gelöscht.
Die entsprechenden DP werden zwar wieder angelegt, jedoch werden die benutzerdefinierten Einstellungen gelöscht.
Alle Einträge wie das Logging per Influx wird zurück gesetzt.

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

2.1.0

### Version of Proxmox

8.0.4

### Operating system running ioBroker

Linux Debian12

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

geloggt wurd es nicht, ist aber sichtbar in der Objektübersicht

**Comment by arteck** [comment]
was heisst den fast ? man kann jetzt einstellen wie der Baum erstellt werden soll. ist im Einstellungen zu finden

**Comment by guergen1** [comment]
OK, wenn da sso gewollt ist, ist das ja ok!
Allerdings setzt die neue Version des Adapters die CPU-Prozente nicht zuverlässig zurück: sprich wenn ich einen Container stope, steht immer noch die alte CPU-Last im IOB

**Comment by arteck** [comment]
installier mal von GIT

**Comment by guergen1** [comment]
Mit "fast" meinte ich, dass das Verzeichnis "node_pve" belibt, der Rest neu erstellt wird. Vielleicht sollte man den Neuaufbau des Baum´s in´m Changelog erwähnen.

**Comment by guergen1** [comment]
> installier mal von GIT

Ja, wenn ich die V von git installiere werden die dynamischen Daten passend geschrieben!
Danke!
Kannst Du also schliessen

**Comment by arteck** [comment]
ich hatte noch ein bug in der io-package.. sollte jetzt passen
