### ISSUE TITLE
has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.proxmox#319]
### The problem

```
State "proxmox.0.storage_proxmox_local-lvm.content" has no existing object, this might lead to an error in future versions
State "proxmox.0.storage_proxmox_local-lvm.content" has no existing object, this might lead to an error in future versions
```

### Version of nodejs

18.18.2

### Version of ioBroker js-controller

5.0.14

### Version of Adapter

2.2.0

### Version of Proxmox

7.2-7

### Operating system running ioBroker

Linux

**Comment by arteck** [comment]
del this object proxmox.0.storage_proxmox_local-lvm
and restart the adapter
