### ISSUE TITLE
Passwort lesbar im Log 

### ISSUE THREAD

**Issue by ipod86** [iobroker-community-adapters/ioBroker.proxmox#340]
### The problem

Im Debuglog werden Benutzernamen und Passwort leserlich ausgegeben.
Zumindest das Passwort sollte unkenntlich gemacht werden......

Hier ein Beispiel (Ich habe den User und das PW jetzt natürlich unkenntlich gemacht):
`2023-12-15 12:55:51.762  - [34mdebug[39m: proxmox.0 (1014320) received 200 response from /access/ticket?username=*****@pam&password=******** with content: {"data":{"cap":{"sdn":{"Permissions.Modify":1,"SDN.Audit":`.......... 

### Version of nodejs

18.19.0

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

2.2.2

### Version of Proxmox

8.3.1

### Operating system running ioBroker

Debian 12 Bookworm 

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by ipod86** [comment]
Auch wenn man einen Fehler im Nutzer oder PW in DEN Settings hat werden die Daten als Warnung im Log leserlich ausgegeben.
Die Meldung kommt dann sekündlich bis man den Adapter stoppt.

**Comment by arteck** [comment]
behoben.. installier die GIT version

**Comment by mcm1957** [comment]
fixed with > 2.2.2
