### ISSUE TITLE
Proxmox CPU Temperatur als Datenpunkt

### ISSUE THREAD

**Issue by mczeus** [iobroker-community-adapters/ioBroker.proxmox#343]
### The problem

wäre es möglich die Temperaturen als Datenpunkte auszugeben!?!

### Version of nodejs

v18.18.2

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

2.2.2

### Version of Proxmox

8.1.3

### Operating system running ioBroker

debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by arteck** [comment]
temperature is not in API ..

**Comment by mczeus** [comment]
ok, schade.
Vielen Dank für den Tipp.
