### ISSUE TITLE
restart des Adapters(error request)

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.proxmox#35]
Seit der v0.5 scheint es Probleme zu geben
auszug aus dem log
`

proxmox.0 | 2019-10-19 10:54:52.997 | info | (14325) starting. Version 0.5.1 in /opt/iobroker/node_modules/iobroker.proxmox, node: v10.16.0
-- | -- | -- | --
host.IoBroker | 2019-10-19 10:54:50.913 | info | instance system.adapter.proxmox.0 started with pid 14325
host.IoBroker | 2019-10-19 10:54:20.892 | info | Restart adapter system.adapter.proxmox.0 because enabled
host.IoBroker | 2019-10-19 10:54:20.891 | info | instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
host.IoBroker | 2019-10-19 10:54:20.891 | error | Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
host.IoBroker | 2019-10-19 10:54:20.891 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
host.IoBroker | 2019-10-19 10:54:20.891 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.IoBroker | 2019-10-19 10:54:20.891 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
host.IoBroker | 2019-10-19 10:54:20.890 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
host.IoBroker | 2019-10-19 10:54:20.889 | error | Caught by controller[0]: TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-10-19 10:54:20.851 | info | (4465) terminating
proxmox.0 | 2019-10-19 10:54:20.788 | info | (4465) cleaned everything up...
proxmox.0 | 2019-10-19 10:54:20.786 | error | at IncomingMessage.emit (events.js:203:15)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Object.onceWrapper (events.js:286:20)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
proxmox.0 | 2019-10-19 10:54:20.786 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
proxmox.0 | 2019-10-19 10:54:20.786 | error | (4465) TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-10-19 10:54:20.784 | error | (4465) uncaught exception: Cannot read property 'name' of undefined

`

**Comment by DutchmanNL** [comment]
passiert das beim Neustart oder wen bestimmte vm/lxc nicht erreichbar sind ?

**Comment by crunchip77** [comment]
Zum einen,  beim Erstellen/Löschen eines Lxc`s taucht der Fehler irgendwann auf, aber auch während des laufenden Betriebes, ohne das etwas am System gemacht/geändert wurde.
Log´s hab ich einige Tage durchgesehen und diesbezüglich nichts weiter gefunden.

**Comment by DutchmanNL** [comment]
> Zum einen, beim Erstellen/Löschen eines Lxc`s taucht der Fehler irgendwann auf, aber auch während des laufenden Betriebes, ohne das etwas am System gemacht/geändert wurde.
> Log´s hab ich einige Tage durchgesehen und diesbezüglich nichts weiter gefunden.

das ist gerade mein Problem ich kan es nicht reproduzieren :/

die stelle im log verweist auf diesen teil im code
https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/master/main.js#L415

tritt der Fehler bei. euch in version 0.5.1 (latest) oder 0.3.2 (stable) auf ?

**Comment by MeisterTR** [comment]
mit dem fix sollte der Fehler eigentlich weg sein

**Comment by ToTXR4Y** [comment]
Also, ich hatte bei mir den Adapter jetzt mehrere Tage auf Debug-Logging stehen. Interessanterweise wurde dort kein Fehler registriert. Gestern habe ich ihn dann wieder auf Info-Logging gestellt und gestern Abend bzw. heute morgen habe ich dann für beide ProxMox Instanzen wieder denselben Fehler in den Logs auftauchen.

**Comment by MeisterTR** [comment]
fixed again in 1.0.2
