### ISSUE TITLE
Exception when proxmox node is down

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.proxmox#36]
2019-10-30 22:14:37.844  - error: proxmox.0 (5465) TypeError: Cannot read property 'uptime' of undefined
    at /opt/iobroker/node_modules/iobroker.proxmox/main.js:375:27
    at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:42:9)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
    at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)

**Comment by DutchmanNL** [comment]
schau ich mir mal an gibt mehrere stellen im code wo das passieren koennte

**Comment by Apollon77** [comment]
Jupp, ist glaube das dritte ticket dieser Art über die Zeit ;-)

**Comment by DutchmanNL** [comment]
> Jupp, ist glaube das dritte ticket dieser Art über die Zeit ;-)

probleem ist das die API null/undefined werte gibt wen eine node abgeschaltet wird, habe den adapter nicht gebaut Abe ruche gerade wo ich das am besten abfangen kan.

passiert das übrigens nur bei abgeschaltete nodes ?
Und nur wen die an war beim adapter start oder immer ?

Crasht der adapter in dem oder ist es nur ne error Warnung ?

(Proxmox wird viel benutzt, alleine in der TS community haben wir innerhalb 6 Monate ueber 50 Systeme aufgesetzt also finde es schon nen sehr wichtigen adapter :)

**Comment by Apollon77** [comment]
der Adapter pollt ja ... ich glaube er crasht inzwischen nicht mehr (aber auch grad nicht sicher).

Am Ende musst Du halt nach jedem "request" prüfen ob der body da ist bzw ein fehler aufgetreten ist. Der Adapter hier macht halt wenige solche Checks

**Comment by MeisterTR** [comment]
Das stimmt, wollte ich auch schon lange nachgeholt haben. Bin im Moment aber ziemlich kurz angebunden...

**Comment by DutchmanNL** [comment]
> Das stimmt, wollte ich auch schon lange nachgeholt haben. Bin im Moment aber ziemlich kurz angebunden...

kein prob ich schau mal ob ich helfen kan, das password problem haben wir ja schonmal gelöst mit dank an Moritz !

**Comment by MeisterTR** [comment]
sollte damit eigentlich behoben sein... leider kann ich es nicht testen hab nur einen node wo alles drauf läuft :)

**Comment by DutchmanNL** [comment]
> sollte damit eigentlich behoben sein... leider kann ich es nicht testen hab nur einen node wo alles drauf läuft :)

dachte ich auch, hab aber. jemanden in der TS-Community der auch mit dieser abfrage. noch den error bekommt wirklich verstehen tu ich das gerade auch nicht :/

**Comment by BuZZy1337** [comment]
Ich würde Array-/Objectsverarbeitung immer in einen try-catch setzen um solche Fehler abzufangen und reagieren zu können..

Es reicht nicht es hier zu tun
https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/514f08a403d1b1bac5a2bee036876016536b169c/main.js#L235-L244
da _setNodes(); async ist..
...
Hier kommt doch das Object welches verarbeitet wird ins Debug-Log..
Was sagt der Logeintrag denn bevor der Fehler kommt?
@DutchmanNL eventuell kann da dein Kontakt aus der TS-Community helfen?
https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/514f08a403d1b1bac5a2bee036876016536b169c/main.js#L365

**Comment by DutchmanNL** [comment]
ich mache bei demjenigen mal ne booby trap und wir werden es. heraus finden
