### ISSUE TITLE
Error message in log file

### ISSUE THREAD

**Issue by simpixo** [iobroker-community-adapters/ioBroker.proxmox#37]
Since a few days I get the following error message in the iobroker log. I have no idea what happend. I did not made any changes

Error message:
`
host.iobroker | 2019-11-01 10:05:48.479 | error | Caught by controller[1]: at IncomingMessage.emit (events.js:203:15)
-- | -- | -- | --
host.iobroker | 2019-11-01 10:05:48.479 | error | Caught by controller[1]: at Object.onceWrapper (events.js:286:20)
host.iobroker | 2019-11-01 10:05:48.479 | error | Caught by controller[1]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.iobroker | 2019-11-01 10:05:48.479 | error | Caught by controller[1]: at Request.emit (events.js:198:13)
host.iobroker | 2019-11-01 10:05:48.479 | error | Caught by controller[1]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: at Request.emit (events.js:198:13)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[1]: TypeError: Cannot read property 'name' of undefined
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
host.iobroker | 2019-11-01 10:05:48.478 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at Request.emit (events.js:198:13)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
host.iobroker | 2019-11-01 10:05:48.477 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
host.iobroker | 2019-11-01 10:05:48.476 | error | Caught by controller[0]: TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-11-01 10:05:48.363 | error | at IncomingMessage.emit (events.js:203:15)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Object.onceWrapper (events.js:286:20)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
proxmox.0 | 2019-11-01 10:05:48.363 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
proxmox.0 | 2019-11-01 10:05:48.363 | error | (11581) TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-11-01 10:05:48.363 | error | (11581) uncaught exception: Cannot read property 'name' of undefined
proxmox.0 | 2019-11-01 10:05:48.357 | error | at IncomingMessage.emit (events.js:203:15)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Object.onceWrapper (events.js:286:20)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
proxmox.0 | 2019-11-01 10:05:48.357 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
proxmox.0 | 2019-11-01 10:05:48.357 | error | (11581) TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-11-01 10:05:48.355 | error | (11581) uncaught exception: Cannot read property 'name' of undefined`

**Comment by DutchmanNL** [comment]
duplicates https://github.com/iobroker-community-adapters/ioBroker.proxmox/issues/36
