### ISSUE TITLE
Units are not correct

### ISSUE THREAD

**Issue by BuZZy1337** [iobroker-community-adapters/ioBroker.proxmox#40]
Proxmox gives RAM etc in Mebibytes
(MiB) not Megabytes (MB).

The graphs shows in MB - the API and the Statuspage shows MiB!

Example 500 MiB is 524,288 MB!:

![image](https://user-images.githubusercontent.com/6979405/70431751-fc0a7780-1a7d-11ea-88fb-0b5a51197887.png)

![image](https://user-images.githubusercontent.com/6979405/70431827-25c39e80-1a7e-11ea-9047-e4aa9861f42c.png)

![image](https://user-images.githubusercontent.com/6979405/70431888-4e4b9880-1a7e-11ea-963a-6291cddb6d16.png)

**Comment by MeisterTR** [comment]
fixed
