### ISSUE TITLE
Start/Stop VM not present

### ISSUE THREAD

**Issue by maddingamer** [iobroker-community-adapters/ioBroker.proxmox#44]
For some reason I don't have the option to start or stop a vm. 
Reinstalling the adapter didn't work either..

![dd](https://user-images.githubusercontent.com/7353549/72838035-d7660a00-3c8f-11ea-8987-072422151185.PNG)

**Comment by maddingamer** [comment]
Using PVE 6.0-11

**Comment by SpookyFishes** [comment]
I just updatet the proxmox adapter to 0.5.1 and after the installation process I can see the new states for my lxc containers.
![grafik](https://user-images.githubusercontent.com/25422320/73109207-cf61d080-3f02-11ea-8522-cbe3eea1f277.png)
I was able to shutdown and start my lxc container.

I'm using Proxmox PVE 6.1-3

**Comment by maddingamer** [comment]
For some reason I had proxmox adapter 0.3.2. But it says it's the latest one.. So I reinstalled via github url and it now works as intended

Maybe it should be investigated why it still says avalible is 0.3.2, even tho 0.5.2 is installed..
 ![version](https://user-images.githubusercontent.com/7353549/73110042-4304dd00-3f05-11ea-9b4b-c8349ec47008.PNG)

**Comment by SpookyFishes** [comment]
If you see 0.3.2 the repositories for the iobroker adapters will be the "stable" repository. You can switch in the settings of iobroker to use the "latest" repository. In this case you will see version 0.5.1 for the proxmox adapter.

**Comment by maddingamer** [comment]
Thanks! Didn't know that one. 
While we are here anyways.. Do you have an idea on how to do a switch (in VIS) indicating status of a VM while a press will turn it on or off, depending if its running? As start and stop are two different objects, I haven't figured out on how to get it working yet...

**Comment by Feuer-sturm** [comment]
I don't have any buttons on my VIS to start / stop a VM so I justed look through the different buttons which can be selected in the VIS editor but I didn't find any button to control two different states.

I think I would solve it with a java script program. Create a new state like "vm1_Powermode". Choose a normal button in VIS to set this state to the values true/false (true for starting, false stopping the vm). After this just create a script which checks the new state "vm1_Powermode".
At the moment I don't have the possibility to write here the real code bit it should work like this

CheckForModification(vm1_Powermode)
If vm1_Powermode == true then setState(proxmox.0.xxx.start,true)
else setState (proxmox.0..stop,true)
