### ISSUE TITLE
PVE Authentication

### ISSUE THREAD

**Issue by SimonFischer04** [iobroker-community-adapters/ioBroker.proxmox#47]
Is it not possible to login with "pve" and not "pam". When I try to login with "pve" I get this error: "401: wrong User data, could not log in, please try again with correct user and pw". After searching around I may found the problem. In your source-code there is this hardcode "@pam":
https://github.com/iobroker-community-adapters/ioBroker.proxmox/blob/514f08a403d1b1bac5a2bee036876016536b169c/lib/proxmox.js#L194
Or did I miss something?

**Comment by SimonFischer04** [comment]
I created a pull request where I changed it.

**Comment by MeisterTR** [comment]
fixed in 1.0.2
