### ISSUE TITLE
Update stable version in repo to 0.5.1

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.proxmox#51]
# Think about update stable version to 0.5.1
**Version**: stable=**0.3.2** (405 days old) => latest=**0.5.1** (169 days old)
**Installs**: stable=**435** (49.66%), latest=**403** (46%), total=**876**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1033)

**Comment by MeisterTR** [comment]
done
