### ISSUE TITLE
[Feature] used_lev for storage_* datapoint

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.proxmox#53]
In addition to state proxmox.0.storage_*.used it would be great to have a used_lev state like proxmox.0.node_pve.memory.used_lev where it is already implemented.

![grafik](https://user-images.githubusercontent.com/25422320/76143298-a93d5d80-6076-11ea-80ba-ee540de14908.png)

**Comment by MeisterTR** [comment]
done
