### ISSUE TITLE
Caught by controller[0]: TypeError: Cannot read property 'uptime' of undefined

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.proxmox#56]
Hi,
i`m using Proxmox 6.1 and the adapter seems to work no more for this verion (before used 5.4, Adapter worked).
I`m receiving following error messages:
`

host.ioBroker2 | 2020-03-31 08:30:37.081 | info | Restart adapter system.adapter.proxmox.0 because enabled
-- | -- | -- | --
host.ioBroker2 | 2020-03-31 08:30:37.081 | info | instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
host.ioBroker2 | 2020-03-31 08:30:37.081 | error | Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught  by controller[0]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
host.ioBroker2 | 2020-03-31 08:30:37.080 | error | Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
host.ioBroker2 | 2020-03-31 08:30:37.079 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:342:27
host.ioBroker2 | 2020-03-31 08:30:37.079 | error | Caught by controller[0]: TypeError: Cannot read property 'uptime' of undefined
proxmox.0 | 2020-03-31 08:30:36.551 | info | (18007) Terminated (NO_ERROR): Without reason

`
Please help :) Thanks MeisterTR

**Comment by Feuer-sturm** [comment]
I am using proxmox version 6.1-7. In iobroker I installed the proxmox adapter vom github during testing this issue https://github.com/iobroker-community-adapters/ioBroker.proxmox/issues/54#issuecomment-597307373

With this version "1.0.2 modified" I don't have any problems in iobroker with the proxmox adapter.

As far as I know this [fix ](https://github.com/iobroker-community-adapters/ioBroker.proxmox/issues/54#issuecomment-597307373) wasn't released in a new adapter version

**Comment by Ilovegym66** [comment]
Nice for you, but here are the Problem with the git Version.. 
I m using proxmox 5.x..

**Comment by Feuer-sturm** [comment]
I just want to help to locate the problem. Until now, no one wrote which proxmox version are installed on your systems or which adapter version you are using. In your last post e.g. you wrote, that you installed the git version and not the released version 1.0.2

For @MeisterTR it would be helpful to get as much information as possible to find and fix the problem.

**Comment by kueppert** [comment]
I'm using the version from git :)
