### ISSUE TITLE
404:Error: getaddrinfo ENOTFOUND https

### ISSUE THREAD

**Issue by david883** [iobroker-community-adapters/ioBroker.proxmox#65]
Hallo, ist es irgendwie möglich bei der Konfiguration die IP Adresse von Proxmox mit https:// einzugeben?

Ich bekomme nur eine Fehlermeldung im Log:
Ohne https:// 404:Error: connect ECONNREFUSED 192.168.178.64:8006
mit https:// 404:Error: getaddrinfo ENOTFOUND https

Danke,

David

**Comment by Apollon77** [comment]
ECONNREFUSED 192.168.178.64:8006 bedeutet das der ioBroker host nicht hin verbinden kann weil die Verbindung abgelehnt wird. Bitte Netzwerk prüfen und as proxmox da auch läuft
