### ISSUE TITLE
Storages requested by node, but stored only via storage name

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.proxmox#68]
Non-Shared stoirages could be online on one host and offiline on an other with the same name (e.g. local-lvm) ... this would lead to strange results.

Non-Shared storages should be stored with their node-id in the object id

**Comment by Apollon77** [comment]
Problem: This will break state-id naming :-(

**Comment by foxriver76** [comment]
> Non-Shared storages should be stored with their node-id in the object id

You mean shared storages should include it ;-)

**Comment by arteck** [comment]
check new structure
![grafik](https://github.com/iobroker-community-adapters/ioBroker.proxmox/assets/6681528/6d30c1f6-3c7b-4b3d-8402-512beb9c52c5)
