### ISSUE TITLE
No discdata at vms

### ISSUE THREAD

**Issue by Pittini** [iobroker-community-adapters/ioBroker.proxmox#86]
Hi, the dps disc and disk_lev remains at zero at vm's, but  at lxc's are working well. This behaviour is acknowledged from other users.
![2021-02-01 12_41_58-Window](https://user-images.githubusercontent.com/51408942/106454385-f1cde880-648a-11eb-8e30-3e7b5264c9f3.png)

**Comment by Feuer-sturm** [comment]
I would be happy if disk and disk_lev can be filled for VMs as well :-)

**Comment by Supermicha81** [comment]
is there any solution jet??

**Comment by arteck** [comment]
its not available sry
