### ISSUE TITLE
ERROR notification in Log when Proxmox is not connected

### ISSUE THREAD

**Issue by martin2704-Ger** [iobroker-community-adapters/ioBroker.proxmox#95]
Not an issue but maybe an enhancement. Changing log level of disconnected Proxmox from Error to Warning.
Background: I'm using Proxmox in a testing environment. Thereof the machine is not running 24/7 and Iobroker logs hundreds of Error messages

**Comment by foxriver76** [comment]
I think if the adapter can not function as expected it should be logged on error level, however I could more imagine to not log the error again and again if the error message stays the same.
